from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from condapm.domain.link import ProjectEnvironmentLink
from condapm.domain.pip_package import PipPackage


class CondaAdapterProtocol(Protocol):
    def environment_exists(self, env_name: str) -> bool: ...
    def create_environment(self, env_name: str, python_version: str) -> None: ...
    def list_environments(self) -> dict[str, Path]: ...


class ConfigStoreProtocol(Protocol):
    def add_link(self, project_path: Path, env_name: str) -> None: ...
    def list_links(self) -> list[ProjectEnvironmentLink]: ...


class PipAdapterProtocol(Protocol):
    def list_packages(self, env_path: Path) -> list[PipPackage]: ...


class LinkEnvironmentConfigStoreProtocol(Protocol):
    def add_link(self, project_path: Path, env_name: str) -> None: ...
    def remove_link(self, project_path: Path, env_name: str) -> None: ...
    def envs_for_project(self, project_path: Path) -> list[str]: ...


class CheckLinksConfigStoreProtocol(Protocol):
    def list_links(self) -> list[Any]: ...
